### ISSUE TITLE
Create HTML

### ISSUE THREAD

**Issue by fforoughi** [Langara-CPSC2350/hw1-frayan-amir-ryu#3]
- Create HTML file that showcases multiple of factors
- Allow the user to submit or not submit how many representatives are to be sorted out to the states
- Allow the user to input ONLY a CSV file that has a list of states and their populations
- Display a table with the list of states and population with their newly added representatives
- Automatically download a CSV file of the updated table

**Comment by ItsYaBoiAmiri** [comment]
All requirements have been completed.
